"use client"
import { AppSidebar } from "@/components/app-sidebar"
import { ChartAreaInteractive } from "@/components/chart-area-interactive"
import { DataTable } from "@/components/data-table"
import { SectionCards } from "@/components/section-cards"
import { SiteHeader } from "@/components/site-header"

import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar"

import data from "./data.json"
import { useEffect, useState } from "react"
import axios from "axios"
import { ExamsTable } from "@/components/exam/exams-table"

export default function Page() {
  const [data, setData] = useState(null)
  const [isLoading, setIsLoading] = useState(false)

  // call the api/analytics
  useEffect(() => {
    const fetchData = async () => {
      try {
        setIsLoading(true)
        const response = await axios.get("/api/analytics")
        if (response?.data?.success) {
          console.log("response", response?.data?.data)
          setData(response?.data?.data)
        }
      } catch (error) {
        console.error("Error fetching data:", error)
        setIsLoading(false)
      } finally {
        setIsLoading(false)
      }
    }
 
    fetchData()
   
  }, [])
  // if loading true and data is null then show loading
  // @ts-ignore
  if (isLoading || !data || !data?.table) {
    return (
      <div className="flex flex-1 items-center justify-center">
        <div className="h-32 w-32 animate-spin rounded-full border-b-2 border-gray-900"></div>
      </div>
    )
  }

  return (
    <SidebarProvider
      style={
        {
          "--sidebar-width": "calc(var(--spacing) * 72)",
          "--header-height": "calc(var(--spacing) * 12)",
        } as React.CSSProperties
      }
    >
      <AppSidebar variant="inset" />
      <SidebarInset>
        <SiteHeader name="Exams" />
        <div className="flex flex-1 flex-col p-6">
        <div className="mb-8">
        <p className="text-gray-500">View and manage quiz results generated by the Exauge Widget</p>
      </div>

      <ExamsTable 
      // @ts-ignore
      examsData={data?.table}
      />
        </div>
      </SidebarInset>
    </SidebarProvider>
  )
}
